apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer #external service reference, assingns service external API adress 
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000 #external IP adress port (must be between 3000-32767)
